name: Claude Code Review

on:
  pull_request:
    types: [opened]
    paths:
      - "setup-ai-context.sh"
      - "AGENTS.md"
      - "README.md"
      - "*.md"
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  claude-review:
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude'))

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

          direct_prompt: |
            Please review this AI Context Standards pull request focusing on:

            SCOPE: Only review files that are actually modified in this specific PR.
            Do not suggest changes to unmodified existing code or include analysis
            of files not changed in this pull request.

            FOCUS AREAS:
            - Shell script best practices and error handling
            - Cross-platform compatibility (macOS, Linux)
            - Security concerns around file operations and network requests
            - User experience and clear error messaging
            - Documentation accuracy and completeness
            - Symlink handling and validation
            - Integration with existing AI agent workflows
            - Backward compatibility with existing setups

            CONTEXT:
            This is a unified AI context management system that:
            - Consolidates separate agent contexts (Claude, Gemini, etc.) into AGENTS.md
            - Supports both global (~/.bjzy) and project-specific setups
            - Uses symlinks for backward compatibility
            - Includes Slack notifications for monitoring
            - Must work reliably across different environments

            Be constructive, helpful, and focus on robustness and user experience.
